### ISSUE TITLE
Not working with installer for installer framework

### ISSUE THREAD

**Issue by juangburgos** [hasboeuf/cuteci#6]
Tried to use it to install intaller framework as follows:

```bash
cuteci --installer QtInstallerFramework-linux-x64.run list
```

got error:

```bash
Skip download: no url provided
Download OK - Qt Installer is ready
FAIL 'NoneType' object has no attribute 'group'
```

**Comment by hasboeuf** [comment]
Hi @juangburgos, thank you for your feedback. As you probably guess, CuteCI ain't design to install Qt Installer Framework but it takes advantage of it to install in command line Qt framework.
I'm closing this ticket as it will not be addressed any soon ;)
